/* ============================================================
   OrionSystems — structured trilingual content
   Edited at runtime by the admin panel (merged from localStorage).
   Sections: services, projects (constellation), oriondb deep-dive,
   pricing (basic/pro/max), clients, testimonials, contact.
   ============================================================ */
window.DATA = {

  /* -------- SERVICES (icon = simpleicons slug, or generic key) -------- */
  services: [
    { icon: "proxmox", title: { uz: "Server ko'tarish & virtualizatsiya", ru: "Развёртывание серверов & виртуализация", en: "Server provisioning & virtualization" },
      desc: { uz: "Fizik server va virtualizatsiya — Proxmox / VMware / Hyper-V.",
              ru: "Физические серверы и виртуализация — Proxmox / VMware / Hyper-V.",
              en: "Physical servers and virtualization — Proxmox / VMware / Hyper-V." },
      long: { uz: "Virtualizatsiya — bitta kuchli serverda o'nlab alohida \"virtual mashina\" ishlatish imkoni. Bu jihozga sarfni kamaytiradi, resursni samarali taqsimlaydi va xizmatlarni bir-biridan ajratib, xavfsizroq qiladi. Biz fizik serverni noldan yig'amiz yoki Proxmox/VMware/Hyper-V klasterini quramiz va kelajakda kengayishga tayyor qilamiz.",
              ru: "Виртуализация — это запуск десятков отдельных «виртуальных машин» на одном мощном сервере. Это снижает расходы на железо, эффективно распределяет ресурсы и изолирует сервисы друг от друга. Мы собираем физический сервер с нуля или строим кластер Proxmox/VMware/Hyper-V, готовый к росту.",
              en: "Virtualization runs dozens of isolated \"virtual machines\" on one powerful server. It cuts hardware costs, allocates resources efficiently and isolates services for safety. We build the physical server from scratch or set up a Proxmox/VMware/Hyper-V cluster ready to scale." },
      points: { uz: ["Fizik server tanlash, yig'ish va sozlash", "Proxmox / VMware ESXi / Hyper-V o'rnatish", "Virtual mashinalar, snapshot va backup", "Klaster va yuqori ishonchlilik (HA)"],
                ru: ["Подбор, сборка и настройка физического сервера", "Установка Proxmox / VMware ESXi / Hyper-V", "Виртуальные машины, снапшоты и бэкап", "Кластер и высокая доступность (HA)"],
                en: ["Physical server selection, assembly and setup", "Proxmox / VMware ESXi / Hyper-V install", "VMs, snapshots and backup", "Clustering and high availability (HA)"] } },

    { icon: "assets/oracle-logo.png", title: { uz: "Oracle baza o'rnatish", ru: "Установка Oracle DB", en: "Oracle DB setup" },
      desc: { uz: "Oracle Database o'rnatish, sozlash va ishchi holatga keltirish — bir nechta versiya va RAC.",
              ru: "Установка, настройка и ввод в эксплуатацию Oracle Database — разные версии и RAC.",
              en: "Installing, configuring and commissioning Oracle Database — multiple versions and RAC." },
      long: { uz: "Oracle Database — yirik korxonalar, banklar va davlat tizimlari uchun dunyodagi eng ishonchli ma'lumotlar bazasi. Uni to'g'ri o'rnatish va sozlash tizim tezligi va barqarorligini hal qiladi. Biz bazani noldan o'rnatamiz, parametrlarni optimallashtiramiz, zaxiralashni yo'lga qo'yamiz va RAC bilan uzluksiz ishlashni ta'minlaymiz.",
              ru: "Oracle Database — самая надёжная в мире СУБД для крупных компаний, банков и госсистем. Правильная установка и настройка определяют скорость и стабильность системы. Мы устанавливаем базу с нуля, оптимизируем параметры, настраиваем резервное копирование и обеспечиваем непрерывность через RAC.",
              en: "Oracle Database is the world's most trusted DBMS for large enterprises, banks and government systems. Correct installation and tuning decide your system's speed and stability. We install the database from scratch, tune parameters, set up backups and ensure uptime with RAC." },
      points: { uz: ["Oracle 19c/21c o'rnatish (Linux)", "Parametr va performance tuning", "RMAN backup va tiklash strategiyasi", "RAC / Data Guard yuqori ishonchlilik"],
                ru: ["Установка Oracle 19c/21c (Linux)", "Тюнинг параметров и производительности", "RMAN-бэкап и стратегия восстановления", "RAC / Data Guard для надёжности"],
                en: ["Oracle 19c/21c install (Linux)", "Parameter & performance tuning", "RMAN backup and recovery strategy", "RAC / Data Guard high availability"] } },

    { icon: "_monitor", title: { uz: "ORIONDB monitoring", ru: "Мониторинг ORIONDB", en: "ORIONDB monitoring" },
      desc: { uz: "Oracle EM o'rnida real-time dashboard — har bir jarayonni kuzatish va alert tizimi.",
              ru: "Real-time дашборд вместо Oracle EM — наблюдение за каждым процессом и оповещения.",
              en: "A real-time dashboard replacing Oracle EM — watch every process with alerting." },
      long: { uz: "ORIONDB — bizning o'z mahsulotimiz: bir nechta bazani bitta oynadan real vaqtda kuzatadi va muammoni mijoz sezishidan oldin aytadi. Svetafor plitkalari, ASH tahlili va Telegram alert bilan jamoangiz har doim vaziyatdan xabardor bo'ladi. Oracle Enterprise Manager o'rnini bosadi, lekin arzonroq va o'zbek tilida.",
              ru: "ORIONDB — наш собственный продукт: наблюдает за несколькими базами из одного окна в реальном времени и сообщает о проблеме раньше клиента. Светофор-плитки, анализ ASH и Telegram-оповещения держат команду в курсе. Заменяет Oracle Enterprise Manager, но дешевле и на узбекском.",
              en: "ORIONDB is our own product: it watches multiple databases from one screen in real time and warns you before the client notices. Traffic-light tiles, ASH analysis and Telegram alerts keep your team informed. It replaces Oracle Enterprise Manager — cheaper and localized." },
      points: { uz: ["50+ baza, real-time WebSocket dashboard", "ASH/Top SQL/lock tahlili", "Telegram alert + daily digest", "Basic/Pro/Max tariflar"],
                ru: ["50+ баз, real-time WebSocket дашборд", "Анализ ASH/Top SQL/локов", "Telegram-оповещения + дайджест", "Тарифы Basic/Pro/Max"],
                en: ["50+ databases, real-time WebSocket dashboard", "ASH/Top SQL/lock analysis", "Telegram alerts + daily digest", "Basic/Pro/Max tiers"] } },

    { icon: "linux", title: { uz: "Linux server", ru: "Linux-серверы", en: "Linux servers" },
      desc: { uz: "Oracle Linux, Ubuntu, RHEL — o'rnatish, qattiqlashtirish va xizmat ko'rsatish.",
              ru: "Oracle Linux, Ubuntu, RHEL — установка, hardening и обслуживание.",
              en: "Oracle Linux, Ubuntu, RHEL — setup, hardening and maintenance." },
      long: { uz: "Linux — serverlar dunyosining asosi: barqaror, xavfsiz va tekin. Deyarli barcha veb-saytlar, bazalar va bulutli xizmatlar Linux'da ishlaydi. Biz serverni o'rnatamiz, xavfsizlik bo'yicha qattiqlashtiramiz (hardening), avtomatlashtiramiz va doimiy yangilanib turishini ta'minlaymiz.",
              ru: "Linux — основа мира серверов: стабильный, безопасный и бесплатный. Почти все сайты, базы и облачные сервисы работают на Linux. Мы устанавливаем сервер, проводим hardening по безопасности, автоматизируем и обеспечиваем регулярные обновления.",
              en: "Linux is the backbone of servers: stable, secure and free. Almost every website, database and cloud service runs on Linux. We install the server, harden it for security, automate it and keep it patched." },
      points: { uz: ["Oracle Linux / Ubuntu / RHEL o'rnatish", "Xavfsizlik hardening (CIS)", "Bash skriptlar bilan avtomatlashtirish", "Yangilanish va xizmat ko'rsatish"],
                ru: ["Установка Oracle Linux / Ubuntu / RHEL", "Hardening безопасности (CIS)", "Автоматизация на bash-скриптах", "Обновления и обслуживание"],
                en: ["Oracle Linux / Ubuntu / RHEL install", "Security hardening (CIS)", "Bash-script automation", "Patching and maintenance"] } },

    { icon: "_windows", title: { uz: "Windows Server", ru: "Windows Server", en: "Windows Server" },
      desc: { uz: "Windows Server o'rnatish, rollar va xizmatlarni sozlash hamda monitoring.",
              ru: "Установка Windows Server, настройка ролей и служб, мониторинг.",
              en: "Windows Server setup, roles and services configuration, monitoring." },
      long: { uz: "Windows Server — ofis muhitida fayl almashish, chop etish, 1C, terminal serverlar va korporativ ilovalar uchun standart yechim. Biz uni o'rnatamiz, kerakli rollarni sozlaymiz, yangilanish va zaxiralashni yo'lga qo'yamiz hamda monitoring ulaymiz.",
              ru: "Windows Server — стандарт для офиса: файлообмен, печать, 1С, терминальные серверы и корпоративные приложения. Мы устанавливаем его, настраиваем нужные роли, налаживаем обновления и бэкап и подключаем мониторинг.",
              en: "Windows Server is the office standard for file sharing, printing, 1C, terminal servers and corporate apps. We install it, configure the required roles, set up updates and backups and add monitoring." },
      points: { uz: ["Windows Server o'rnatish va litsenziya", "Fayl/Print/Terminal (RDS) rollari", "Backup va yangilanish siyosati", "Holat monitoringi"],
                ru: ["Установка и лицензирование Windows Server", "Роли Файл/Печать/Терминал (RDS)", "Политика бэкапа и обновлений", "Мониторинг состояния"],
                en: ["Windows Server install and licensing", "File/Print/Terminal (RDS) roles", "Backup and update policy", "Health monitoring"] } },

    { icon: "_ad", title: { uz: "Active Directory", ru: "Active Directory", en: "Active Directory" },
      desc: { uz: "Domen, foydalanuvchilar, guruhlar va siyosatlar (GPO) — markazlashgan boshqaruv.",
              ru: "Домен, пользователи, группы и политики (GPO) — централизованное управление.",
              en: "Domain, users, groups and policies (GPO) — centralized management." },
      long: { uz: "Active Directory — kompaniyadagi barcha kompyuter va xodimlarni bitta joydan boshqarish tizimi. Har bir xodim bitta login bilan kiradi, kim nimaga ruxsati borligini admin belgilaydi, parol va xavfsizlik qoidalari (GPO) bir marta o'rnatilib hammaga tarqaladi. Bu — tartib, xavfsizlik va vaqt tejash.",
              ru: "Active Directory — система управления всеми компьютерами и сотрудниками компании из одного места. Каждый сотрудник входит по одному логину, админ задаёт права доступа, а правила паролей и безопасности (GPO) настраиваются один раз и распространяются на всех. Это порядок, безопасность и экономия времени.",
              en: "Active Directory manages every computer and employee in a company from one place. Each employee signs in with a single login, the admin sets who can access what, and password/security rules (GPO) are configured once and pushed to everyone. It means order, security and saved time." },
      points: { uz: ["Domen kontroller o'rnatish (DC)", "Foydalanuvchi/guruh va OU tuzilmasi", "Group Policy (GPO) xavfsizlik qoidalari", "DNS, DHCP va replikatsiya"],
                ru: ["Установка контроллера домена (DC)", "Структура пользователей/групп и OU", "Политики безопасности Group Policy (GPO)", "DNS, DHCP и репликация"],
                en: ["Domain controller (DC) setup", "User/group and OU structure", "Group Policy (GPO) security rules", "DNS, DHCP and replication"] } },

    { icon: "_devops", title: { uz: "DevOps xizmati", ru: "DevOps-услуги", en: "DevOps services" },
      desc: { uz: "CI/CD, konteynerlash, avtomatlashtirish va infratuzilmani kod sifatida boshqarish.",
              ru: "CI/CD, контейнеризация, автоматизация и инфраструктура как код.",
              en: "CI/CD, containerization, automation and infrastructure as code." },
      long: { uz: "DevOps — dasturni yozishdan serverga chiqarishgacha bo'lgan yo'lni avtomatlashtirish madaniyati. Bu xatolarni kamaytiradi, yangilanishlarni soatlardan daqiqalarga qisqartiradi va jamoaning tezligini oshiradi. Biz quvurlar (pipeline), konteynerlar va \"infratuzilma kod sifatida\" yondashuvini joriy qilamiz.",
              ru: "DevOps — культура автоматизации пути от написания кода до выката на сервер. Это снижает ошибки, сокращает релизы с часов до минут и ускоряет команду. Мы внедряем пайплайны, контейнеры и подход «инфраструктура как код».",
              en: "DevOps is the culture of automating the path from writing code to shipping it to servers. It reduces errors, cuts releases from hours to minutes and speeds up the team. We implement pipelines, containers and infrastructure-as-code." },
      points: { uz: ["CI/CD quvurlar (pipeline)", "Docker konteynerlash", "Infrastructure as Code", "Avtomatik deploy va rollback"],
                ru: ["CI/CD пайплайны", "Контейнеризация Docker", "Infrastructure as Code", "Автодеплой и откат"],
                en: ["CI/CD pipelines", "Docker containerization", "Infrastructure as Code", "Automated deploy and rollback"] } },

    { icon: "gitlab", title: { uz: "GitLab CI/CD", ru: "GitLab CI/CD", en: "GitLab CI/CD" },
      desc: { uz: "Avtomatik build/test/deploy quvuri. Dev zona va Prod zona uchun alohida stagelar.",
              ru: "Автоматический конвейер build/test/deploy. Отдельные стейджи для Dev и Prod.",
              en: "Automated build/test/deploy pipeline. Separate Dev and Prod stages." },
      long: { uz: "GitLab CI/CD — kod har o'zgartirilganda uni avtomatik yig'adi, tekshiradi va serverga chiqaradi. Biz Dev zona (sinov) va Prod zona (ishlab chiqarish) uchun alohida bosqichlar quramiz: yangilik avval sinov muhitiga, so'ng faqat tasdiqlash bilan ishlab chiqarishga o'tadi — xato bo'lsa bir bosishda orqaga qaytariladi.",
              ru: "GitLab CI/CD автоматически собирает, проверяет и выкатывает код при каждом изменении. Мы строим отдельные стадии для Dev-зоны (тест) и Prod-зоны (продакшен): изменение сначала идёт в тест, затем только с подтверждением в продакшен — при ошибке откат в один клик.",
              en: "GitLab CI/CD automatically builds, tests and deploys code on every change. We build separate stages for the Dev zone (testing) and Prod zone (production): a change goes to test first, then to production only with approval — with one-click rollback on failure." },
      points: { uz: ["Build → Test → Dev → Prod stagelar", "Manual approval va rollback", "Docker registry integratsiyasi", "Dev/Prod muhitlari ajratilgan"],
                ru: ["Стадии Build → Test → Dev → Prod", "Ручное подтверждение и откат", "Интеграция Docker registry", "Разделённые среды Dev/Prod"],
                en: ["Build → Test → Dev → Prod stages", "Manual approval and rollback", "Docker registry integration", "Separated Dev/Prod environments"] } },

    { icon: "grafana", title: { uz: "Grafana dashboard", ru: "Дашборды Grafana", en: "Grafana dashboards" },
      desc: { uz: "CPU/RAM/disk/tarmoq va xizmatlar uchun chiroyli, real vaqtli panellar.",
              ru: "Красивые real-time панели для CPU/RAM/диска/сети и сервисов.",
              en: "Beautiful real-time panels for CPU/RAM/disk/network and services." },
      long: { uz: "Grafana — raqamlarni chiroyli, tushunarli grafiklarga aylantiradigan dunyodagi eng mashhur dashboard vositasi. Bir ekranda butun infratuzilmangiz holatini ko'rasiz: yuk, xotira, disk, tarmoq va xizmatlar. Muammo paydo bo'lsa, rang va alert orqali darhol bilinadi.",
              ru: "Grafana — самый популярный в мире инструмент дашбордов, превращающий цифры в понятные графики. На одном экране видно состояние всей инфраструктуры: нагрузка, память, диск, сеть и сервисы. При проблеме сразу видно по цвету и оповещению.",
              en: "Grafana is the world's most popular dashboard tool, turning numbers into clear graphs. One screen shows your whole infrastructure: load, memory, disk, network and services. Problems stand out instantly via color and alerts." },
      points: { uz: ["Maxsus dashboard dizayni", "Prometheus/Zabbix/baza manbalari", "Alert qoidalari va xabarnomalar", "Jamoaga moslangan ko'rinishlar"],
                ru: ["Дизайн кастомных дашбордов", "Источники Prometheus/Zabbix/БД", "Правила алертов и оповещения", "Виды под команду"],
                en: ["Custom dashboard design", "Prometheus/Zabbix/DB sources", "Alert rules and notifications", "Team-tailored views"] } },

    { icon: "zabbix", title: { uz: "Zabbix monitoring", ru: "Мониторинг Zabbix", en: "Zabbix monitoring" },
      desc: { uz: "Zabbix o'rnatish, template, trigger va xabarnomalarni to'liq sozlash.",
              ru: "Установка Zabbix, шаблоны, триггеры и полная настройка оповещений.",
              en: "Zabbix setup, templates, triggers and full alerting configuration." },
      long: { uz: "Zabbix — serverlar, tarmoq qurilmalari va xizmatlarni kuzatuvchi kuchli, tekin monitoring tizimi. U minglab metrikani yig'adi, belgilangan chegaradan oshsa avtomatik ogohlantiradi. Biz uni o'rnatamiz, qurilmalaringizga moslab template va triggerlarni sozlaymiz.",
              ru: "Zabbix — мощная бесплатная система мониторинга серверов, сетевого оборудования и сервисов. Она собирает тысячи метрик и автоматически предупреждает при превышении порогов. Мы устанавливаем её и настраиваем шаблоны и триггеры под ваше оборудование.",
              en: "Zabbix is a powerful, free monitoring system for servers, network gear and services. It collects thousands of metrics and auto-alerts when thresholds are crossed. We install it and tune templates and triggers for your equipment." },
      points: { uz: ["Zabbix server o'rnatish", "Host, template va trigger sozlash", "SNMP va agent monitoringi", "Email/Telegram xabarnomalar"],
                ru: ["Установка Zabbix-сервера", "Настройка хостов, шаблонов и триггеров", "SNMP и агентский мониторинг", "Оповещения Email/Telegram"],
                en: ["Zabbix server install", "Host, template and trigger setup", "SNMP and agent monitoring", "Email/Telegram notifications"] } },

    { icon: "prometheus", title: { uz: "Prometheus", ru: "Prometheus", en: "Prometheus" },
      desc: { uz: "node_exporter, metrikalar yig'ish, PromQL va Grafana bilan integratsiya.",
              ru: "node_exporter, сбор метрик, PromQL и интеграция с Grafana.",
              en: "node_exporter, metrics collection, PromQL and Grafana integration." },
      long: { uz: "Prometheus — zamonaviy bulut va konteyner muhitlari uchun standart metrika yig'uvchi tizim. U serverlardan ko'rsatkichlarni to'playdi va Grafana bilan birga kuchli monitoring beradi. Konteynerlar va mikroservislar uchun ayniqsa qulay.",
              ru: "Prometheus — стандарт сбора метрик для современных облачных и контейнерных сред. Он собирает показатели с серверов и вместе с Grafana даёт мощный мониторинг. Особенно удобен для контейнеров и микросервисов.",
              en: "Prometheus is the standard metrics collector for modern cloud and container environments. It scrapes metrics from servers and, with Grafana, delivers powerful monitoring. Especially handy for containers and microservices." },
      points: { uz: ["Prometheus + node_exporter o'rnatish", "PromQL so'rovlar va qoidalar", "Alertmanager xabarnomalari", "Grafana bilan integratsiya"],
                ru: ["Установка Prometheus + node_exporter", "Запросы и правила PromQL", "Оповещения Alertmanager", "Интеграция с Grafana"],
                en: ["Prometheus + node_exporter setup", "PromQL queries and rules", "Alertmanager notifications", "Grafana integration"] } },

    { icon: "_network", title: { uz: "Tarmoq nazorati", ru: "Мониторинг сети", en: "Network monitoring" },
      desc: { uz: "Tarmoq topologiyasi, kommutator/router holati va bandlik uchun dashboardlar.",
              ru: "Дашборды топологии сети, состояния коммутаторов/роутеров и нагрузки.",
              en: "Dashboards for network topology, switch/router health and bandwidth." },
      long: { uz: "Tarmoq — butun IT infratuzilmaning qon tomiri; u sekinlashsa, hamma narsa sekinlashadi. Biz kommutator, router va kanallarni kuzatuvchi tizim quramiz: qaysi qurilma ishlamayapti, qayerda bandlik yuqori, qayerda kechikish bor — hammasi vizual xaritada ko'rinadi.",
              ru: "Сеть — это кровеносная система всей IT-инфраструктуры; если она тормозит, тормозит всё. Мы строим систему мониторинга коммутаторов, роутеров и каналов: какое устройство не работает, где высокая загрузка, где задержки — всё на визуальной карте.",
              en: "The network is the bloodstream of all IT; if it slows, everything slows. We build monitoring for switches, routers and links: which device is down, where bandwidth is high, where latency spikes — all on a visual map." },
      points: { uz: ["SNMP orqali qurilma monitoringi", "Topologiya xaritasi", "Bandlik va latency kuzatuvi", "Uzilishda darhol alert"],
                ru: ["Мониторинг устройств по SNMP", "Карта топологии", "Контроль загрузки и задержек", "Мгновенный алерт при сбое"],
                en: ["SNMP device monitoring", "Topology map", "Bandwidth and latency tracking", "Instant alert on outage"] } },

    { icon: "elasticsearch", title: { uz: "Elasticsearch", ru: "Elasticsearch", en: "Elasticsearch" },
      desc: { uz: "Log yig'ish, qidiruv va tahlil uchun Elasticsearch klasteri.",
              ru: "Кластер Elasticsearch для сбора логов, поиска и аналитики.",
              en: "Elasticsearch cluster for log aggregation, search and analytics." },
      long: { uz: "Elasticsearch — millionlab log va hujjat orasidan bir soniyada qidirish imkonini beruvchi tizim. Barcha serverlaringiz loglarini bitta joyga yig'ib, muammoni tez topishga yordam beradi. Kibana bilan birga kuchli tahlil va vizualizatsiya beradi.",
              ru: "Elasticsearch позволяет за секунду искать среди миллионов логов и документов. Он собирает логи всех серверов в одно место и помогает быстро находить проблемы. Вместе с Kibana даёт мощную аналитику и визуализацию.",
              en: "Elasticsearch searches through millions of logs and documents in a second. It centralizes logs from all your servers and helps find problems fast. With Kibana it delivers powerful analytics and visualization." },
      points: { uz: ["Elasticsearch klaster o'rnatish", "Logstash/Beats bilan log yig'ish", "Kibana dashboard va qidiruv", "Saqlash va indeks siyosati"],
                ru: ["Установка кластера Elasticsearch", "Сбор логов через Logstash/Beats", "Дашборды и поиск в Kibana", "Политика хранения и индексов"],
                en: ["Elasticsearch cluster setup", "Log shipping via Logstash/Beats", "Kibana dashboards and search", "Retention and index policy"] } },

    { icon: "portainer", title: { uz: "Portainer", ru: "Portainer", en: "Portainer" },
      desc: { uz: "Docker/Swarm konteynerlarni vizual boshqarish va stack deploy.",
              ru: "Визуальное управление контейнерами Docker/Swarm и деплой стеков.",
              en: "Visual management of Docker/Swarm containers and stack deployment." },
      long: { uz: "Portainer — Docker konteynerlarni murakkab buyruqlarsiz, qulay vizual oynadan boshqarish vositasi. Konteynerlarni ishga tushirish, log ko'rish, resurs nazorati va deploy — hammasi sichqoncha bilan. Texnik bo'lmagan xodim ham holatni kuzata oladi.",
              ru: "Portainer — управление Docker-контейнерами через удобное визуальное окно, без сложных команд. Запуск контейнеров, просмотр логов, контроль ресурсов и деплой — всё мышкой. Даже не технический сотрудник видит состояние.",
              en: "Portainer manages Docker containers through a convenient visual UI, no complex commands. Start containers, view logs, watch resources and deploy — all with the mouse. Even a non-technical user can see the status." },
      points: { uz: ["Portainer o'rnatish (Docker/Swarm)", "Stack va konteyner deploy", "Resurs va log monitoringi", "Rolga asoslangan kirish"],
                ru: ["Установка Portainer (Docker/Swarm)", "Деплой стеков и контейнеров", "Мониторинг ресурсов и логов", "Доступ по ролям"],
                en: ["Portainer install (Docker/Swarm)", "Stack and container deploy", "Resource and log monitoring", "Role-based access"] } },

    { icon: "uptimekuma", title: { uz: "Uptime Kuma", ru: "Uptime Kuma", en: "Uptime Kuma" },
      desc: { uz: "Xizmatlar uptime monitoringi, status sahifa va tezkor xabarnomalar.",
              ru: "Мониторинг аптайма сервисов, страница статуса и быстрые оповещения.",
              en: "Service uptime monitoring, status page and instant notifications." },
      long: { uz: "Uptime Kuma — sayt va xizmatlaringiz ishlab turibdimi yoki yo'qmi — har daqiqada tekshiradigan sodda va chiroyli vosita. Xizmat to'xtasa, bir necha soniyada Telegram yoki emailga xabar keladi. Mijozlar uchun chiroyli \"status sahifa\" ham yaratiladi.",
              ru: "Uptime Kuma — простой и красивый инструмент, проверяющий каждую минуту, работают ли ваши сайты и сервисы. Если сервис упал, за секунды приходит уведомление в Telegram или email. Создаётся и красивая «страница статуса» для клиентов.",
              en: "Uptime Kuma is a simple, elegant tool that checks every minute whether your sites and services are up. If something goes down, you get a Telegram or email alert in seconds. It also builds a clean public status page for clients." },
      points: { uz: ["Sayt/port/baza monitoringi", "Telegram/email xabarnomalar", "Ommaviy status sahifasi", "SSL muddati nazorati"],
                ru: ["Мониторинг сайтов/портов/баз", "Оповещения Telegram/email", "Публичная страница статуса", "Контроль срока SSL"],
                en: ["Site/port/database monitoring", "Telegram/email alerts", "Public status page", "SSL expiry tracking"] } },

    { icon: "rabbitmq", title: { uz: "RabbitMQ", ru: "RabbitMQ", en: "RabbitMQ" },
      desc: { uz: "Message broker o'rnatish, navbatlar, clustering va monitoring.",
              ru: "Установка брокера сообщений, очереди, кластеризация и мониторинг.",
              en: "Message broker setup, queues, clustering and monitoring." },
      long: { uz: "RabbitMQ — ilovalar o'rtasida xabar va vazifalarni ishonchli yetkazib beruvchi \"pochta\" tizimi. Tizimning bir qismi band bo'lsa ham, vazifalar navbatda saqlanadi va yo'qolmaydi. Yuqori yuklamali va taqsimlangan tizimlar uchun zarur.",
              ru: "RabbitMQ — «почтовая» система, надёжно доставляющая сообщения и задачи между приложениями. Даже если часть системы занята, задачи хранятся в очереди и не теряются. Необходим для высоконагруженных и распределённых систем.",
              en: "RabbitMQ is a \"postal\" system that reliably delivers messages and tasks between applications. Even if part of the system is busy, tasks stay queued and aren't lost. Essential for high-load and distributed systems." },
      points: { uz: ["RabbitMQ o'rnatish va sozlash", "Navbat va exchange dizayni", "Clustering va yuqori ishonchlilik", "Monitoring va alert"],
                ru: ["Установка и настройка RabbitMQ", "Дизайн очередей и exchange", "Кластеризация и надёжность", "Мониторинг и алерты"],
                en: ["RabbitMQ install and setup", "Queue and exchange design", "Clustering and high availability", "Monitoring and alerts"] } },

    { icon: "nginx", title: { uz: "Nginx", ru: "Nginx", en: "Nginx" },
      desc: { uz: "Reverse proxy, load balancing, SSL/TLS termination va keshlash.",
              ru: "Reverse proxy, балансировка, SSL/TLS-терминация и кэширование.",
              en: "Reverse proxy, load balancing, SSL/TLS termination and caching." },
      long: { uz: "Nginx — saytlaringiz oldida turuvchi tez va ishonchli \"darvozabon\". U so'rovlarni bir nechta serverga taqsimlaydi (yuk muvozanati), HTTPS (SSL) ni ta'minlaydi va kontentni keshlab tezlikni oshiradi. Internet trafikning katta qismi Nginx orqali o'tadi.",
              ru: "Nginx — быстрый и надёжный «привратник» перед вашими сайтами. Он распределяет запросы между серверами (балансировка), обеспечивает HTTPS (SSL) и ускоряет за счёт кэширования. Через Nginx проходит большая часть интернет-трафика.",
              en: "Nginx is the fast, reliable \"gatekeeper\" in front of your sites. It distributes requests across servers (load balancing), provides HTTPS (SSL) and speeds things up with caching. A large share of internet traffic flows through Nginx." },
      points: { uz: ["Reverse proxy sozlash", "Load balancing (yuk muvozanati)", "SSL/TLS sertifikat (Let's Encrypt)", "Keshlash va tezlashtirish"],
                ru: ["Настройка reverse proxy", "Балансировка нагрузки", "SSL/TLS-сертификат (Let's Encrypt)", "Кэширование и ускорение"],
                en: ["Reverse proxy setup", "Load balancing", "SSL/TLS certificate (Let's Encrypt)", "Caching and acceleration"] } },

    { icon: "telegram", title: { uz: "Telegram botlar", ru: "Telegram-боты", en: "Telegram bots" },
      desc: { uz: "Alert botlar, avtomatlashtirish va xizmatlarni Telegram orqali boshqarish.",
              ru: "Боты оповещений, автоматизация и управление сервисами через Telegram.",
              en: "Alert bots, automation and managing services through Telegram." },
      long: { uz: "Telegram bot — kompaniyangiz jarayonlarini telefon orqali boshqarish va kuzatishning eng tez yo'li. Kritik holatda guruhga avtomatik xabar keladi, tugma bosib javob berasiz; hisobotlar, so'rovlar va vazifalar ham bot orqali avtomatlashtiriladi.",
              ru: "Telegram-бот — самый быстрый способ управлять процессами компании и следить за ними с телефона. При критической ситуации в группу приходит авто-сообщение, вы реагируете кнопкой; отчёты, заявки и задачи тоже автоматизируются через бота.",
              en: "A Telegram bot is the fastest way to run and watch your company's processes from your phone. Critical events auto-post to a group and you respond with a button; reports, requests and tasks are automated through the bot too." },
      points: { uz: ["Alert va monitoring botlari", "Inline tugmalar bilan boshqaruv", "Hisobot va so'rov avtomatizatsiyasi", "Tizimlar bilan integratsiya"],
                ru: ["Боты алертов и мониторинга", "Управление inline-кнопками", "Автоматизация отчётов и заявок", "Интеграция с системами"],
                en: ["Alert and monitoring bots", "Inline-button control", "Report and request automation", "Integration with systems"] } },

    { icon: "_chat", title: { uz: "Lokal chat (Orion Chat)", ru: "Локальный чат (Orion Chat)", en: "Local chat (Orion Chat)" },
      desc: { uz: "Rocket.Chat/Mattermost asosida lokal korporativ messenjer + nazorat paneli.",
              ru: "Локальный корпоративный мессенджер на Rocket.Chat/Mattermost + панель контроля.",
              en: "On-prem corporate messenger on Rocket.Chat/Mattermost + control panel." },
      long: { uz: "Orion Chat — Telegramning barcha qulayliklariga ega, lekin to'liq sizning serveringizda ishlaydigan korporativ messenjer. Yozishmalar kompaniyadan tashqariga chiqmaydi, ma'lumotlar sizniki. Maxsus admin panel orqali har bir foydalanuvchi faoliyatini real vaqtda kuzatish mumkin.",
              ru: "Orion Chat — корпоративный мессенджер со всеми удобствами Telegram, но работающий полностью на вашем сервере. Переписка не выходит за пределы компании, данные — ваши. Через специальную админ-панель можно следить за активностью каждого пользователя в реальном времени.",
              en: "Orion Chat is a corporate messenger with all of Telegram's convenience, but running fully on your own server. Conversations never leave the company; the data is yours. A dedicated admin panel lets you watch each user's activity in real time." },
      points: { uz: ["Rocket.Chat/Mattermost lokal o'rnatish", "Shaxsiy/guruh/kanal, voice/video", "LDAP/AD bilan yagona login", "Faoliyat nazorat paneli + audit"],
                ru: ["Локальная установка Rocket.Chat/Mattermost", "Личные/группы/каналы, voice/video", "Единый вход через LDAP/AD", "Панель контроля активности + аудит"],
                en: ["On-prem Rocket.Chat/Mattermost", "DMs/groups/channels, voice/video", "Single sign-on via LDAP/AD", "Activity control panel + audit"] } },

    { icon: "_server", title: { uz: "Server monitoring", ru: "Мониторинг серверов", en: "Server monitoring" },
      desc: { uz: "Fizik va virtual serverlar: CPU, RAM, disk, IO, jarayonlar — bir joyda.",
              ru: "Физические и виртуальные серверы: CPU, RAM, диск, IO, процессы — в одном месте.",
              en: "Physical and virtual servers: CPU, RAM, disk, IO, processes — in one place." },
      long: { uz: "Server monitoring — serverlaringiz \"sog'lig'i\"ni doimiy tekshirib turish. Disk to'lib qolishidan, xotira yetishmasligidan yoki yuk oshib ketishidan oldin ogohlantiradi. Bu kutilmagan to'xtashlarning oldini oladi va tizim doimo barqaror ishlashini ta'minlaydi.",
              ru: "Мониторинг серверов — постоянная проверка «здоровья» ваших серверов. Предупреждает заранее о заполнении диска, нехватке памяти или росте нагрузки. Это предотвращает неожиданные простои и держит систему стабильной.",
              en: "Server monitoring continuously checks your servers' \"health\". It warns ahead of a full disk, low memory or rising load. This prevents unexpected downtime and keeps the system stable." },
      points: { uz: ["CPU/RAM/disk/IO/jarayon kuzatuvi", "SSH yoki Prometheus orqali", "Chegara va alert sozlash", "Tarixiy grafiklar"],
                ru: ["Контроль CPU/RAM/диск/IO/процессы", "Через SSH или Prometheus", "Настройка порогов и алертов", "Исторические графики"],
                en: ["CPU/RAM/disk/IO/process tracking", "Via SSH or Prometheus", "Threshold and alert setup", "Historical graphs"] } },

    { icon: "_camera", title: { uz: "Hikvision kamera sozlash", ru: "Настройка камер Hikvision", en: "Hikvision camera setup" },
      desc: { uz: "Videokuzatuv: kamera, NVR/DVR o'rnatish, sozlash va masofadan ko'rish.",
              ru: "Видеонаблюдение: установка камер, NVR/DVR, настройка и удалённый просмотр.",
              en: "CCTV: cameras, NVR/DVR install, configuration and remote viewing." },
      long: { uz: "Videokuzatuv — ofis, ombor yoki obyekt xavfsizligining asosi. Biz Hikvision kameralarini o'rnatamiz va sozlaymiz: yozuvni NVR/DVR'ga saqlash, harakat aniqlanganda ogohlantirish va telefon/kompyuterdan masofadan jonli ko'rish. Tarmoq va kirish xavfsizligi ham to'g'ri sozlanadi.",
              ru: "Видеонаблюдение — основа безопасности офиса, склада или объекта. Мы устанавливаем и настраиваем камеры Hikvision: запись на NVR/DVR, оповещение при движении и удалённый онлайн-просмотр с телефона/компьютера. Сеть и безопасность доступа тоже настраиваются правильно.",
              en: "CCTV is the foundation of office, warehouse or site security. We install and configure Hikvision cameras: NVR/DVR recording, motion-detection alerts and remote live viewing from phone/PC. Network and access security are configured properly too." },
      points: { uz: ["Kamera va NVR/DVR o'rnatish", "Yozuv, harakat va arxiv sozlash", "Masofadan ko'rish (mobil/PC)", "Tarmoq va parol xavfsizligi"],
                ru: ["Установка камер и NVR/DVR", "Настройка записи, движения и архива", "Удалённый просмотр (моб./ПК)", "Сетевая и парольная безопасность"],
                en: ["Camera and NVR/DVR install", "Recording, motion and archive setup", "Remote viewing (mobile/PC)", "Network and password security"] } },

    { icon: "_headset", title: { uz: "Call center + admin panel", ru: "Call-центр + админ-панель", en: "Call center + admin dashboard" },
      desc: { uz: "IP-telefoniya call center va qo'ng'iroqlarni kuzatuvchi admin dashboard.",
              ru: "Call-центр на IP-телефонии и админ-дашборд контроля звонков.",
              en: "IP-telephony call center and a call-tracking admin dashboard." },
      long: { uz: "Call center — mijozlar bilan ishlashni tartibga soluvchi telefoniya tizimi. Qo'ng'iroqlar operatorlarga taqsimlanadi, navbat va yozuv yuritiladi. Admin dashboard orqali rahbar har bir operator nechta qo'ng'iroq qabul qilgani, o'rtacha vaqt va o'tkazib yuborilgan chaqiruvlarni real vaqtda ko'radi — sifat va samaradorlik nazoratda.",
              ru: "Call-центр — телефонная система, упорядочивающая работу с клиентами. Звонки распределяются по операторам, ведётся очередь и запись. Через админ-дашборд руководитель в реальном времени видит, сколько звонков принял каждый оператор, среднее время и пропущенные — качество и эффективность под контролем.",
              en: "A call center is a telephony system that organizes customer interactions. Calls are routed to agents, with queueing and recording. An admin dashboard shows managers in real time how many calls each agent handled, average time and missed calls — quality and efficiency under control." },
      points: { uz: ["IP-telefoniya (Asterisk/FreePBX) o'rnatish", "Qo'ng'iroq taqsimoti, navbat, yozuv", "Real-time admin dashboard va hisobotlar", "CRM/Telegram bilan integratsiya"],
                ru: ["Установка IP-телефонии (Asterisk/FreePBX)", "Распределение звонков, очередь, запись", "Real-time админ-дашборд и отчёты", "Интеграция с CRM/Telegram"],
                en: ["IP telephony (Asterisk/FreePBX) setup", "Call routing, queue, recording", "Real-time admin dashboard and reports", "CRM/Telegram integration"] } },

    { icon: "_it", title: { uz: "IT autsorsing", ru: "IT-аутсорсинг", en: "IT outsourcing" },
      desc: { uz: "To'liq IT qo'llab-quvvatlash, konsalting va infratuzilma audit.",
              ru: "Полная IT-поддержка, консалтинг и аудит инфраструктуры.",
              en: "Full IT support, consulting and infrastructure audits." },
      long: { uz: "IT autsorsing — o'z IT bo'limingiz bo'lmasa ham, butun IT muhitingizni biz qarab turamiz. Doimiy qo'llab-quvvatlash, profilaktika, muammolarni tez hal qilish va texnik maslahatlar — kompaniyangiz asosiy ishiga e'tibor qaratadi, IT bizning zimmamizда.",
              ru: "IT-аутсорсинг — даже без своего IT-отдела мы берём на себя всю вашу IT-среду. Постоянная поддержка, профилактика, быстрое решение проблем и технические консультации — вы фокусируетесь на основном бизнесе, IT на нас.",
              en: "IT outsourcing — even without an in-house IT team, we take care of your entire IT environment. Ongoing support, preventive maintenance, fast issue resolution and technical advice — you focus on your core business, we handle IT." },
      points: { uz: ["Infratuzilma auditi va hujjatlash", "Doimiy qo'llab-quvvatlash (SLA)", "Profilaktika va xavfsizlik", "Texnik konsalting"],
                ru: ["Аудит и документирование инфраструктуры", "Постоянная поддержка (SLA)", "Профилактика и безопасность", "Технический консалтинг"],
                en: ["Infrastructure audit and documentation", "Ongoing support (SLA)", "Preventive maintenance and security", "Technical consulting"] } },
  ],

  /* -------- PROJECTS (constellation nodes) --------
     x,y are normalized 0..1 inside the constellation box (Orion shape).
     Each node is clickable → project.html?id=<id> */
  projects: [
    { id: "oriondb", star: "Betelgeuse", x: 0.23, y: 0.24, accent: "#ff7a59", size: 30, featured: true,
      image: "assets/oriondb.svg",
      name: { uz: "ORIONDB", ru: "ORIONDB", en: "ORIONDB" },
      tagline: { uz: "Oracle EM o'rnida real-time monitoring", ru: "Real-time мониторинг вместо Oracle EM", en: "Real-time monitoring, an Oracle EM replacement" },
      desc: { uz: "Bir nechta Oracle (va boshqa) bazani bitta oynadan real vaqtda kuzatuvchi professional dashboard. Svetafor indikatorlar, ASH tahlili, Telegram alert va Prometheus/Grafana integratsiyasi.",
              ru: "Профессиональный дашборд для мониторинга нескольких баз Oracle (и не только) из одного окна в реальном времени. Светофоры, анализ ASH, Telegram-оповещения и интеграция с Prometheus/Grafana.",
              en: "A professional dashboard monitoring multiple Oracle (and other) databases from one screen in real time. Traffic-light tiles, ASH analysis, Telegram alerts and Prometheus/Grafana integration." },
      tags: ["Oracle", "PostgreSQL", "WebSocket", "Telegram", "Prometheus"] },

    { id: "orion-chat", star: "Rigel", x: 0.73, y: 0.87, accent: "#9ec5ff", size: 26,
      image: "assets/orion-chat.svg",
      name: { uz: "Orion Chat", ru: "Orion Chat", en: "Orion Chat" },
      tagline: { uz: "Lokal korporativ messenjer", ru: "Локальный корпоративный мессенджер", en: "On-prem corporate messenger" },
      desc: { uz: "Rocket.Chat/Mattermost asosidagi to'liq lokal chat — Telegramdagi barcha imkoniyatlar, lekin sizning serveringizda. Har bir foydalanuvchi faoliyatini real vaqtda kuzatuvchi maxsus nazorat paneli bilan.",
              ru: "Полностью локальный чат на базе Rocket.Chat/Mattermost — все возможности Telegram, но на вашем сервере. С отдельной панелью контроля активности каждого пользователя в реальном времени.",
              en: "A fully on-prem chat built on Rocket.Chat/Mattermost — all of Telegram's features, but on your server. With a dedicated panel tracking every user's activity in real time." },
      tags: ["Rocket.Chat", "Mattermost", "Docker", "LDAP/AD", "Audit"] },

    { id: "monitoring-stack", star: "Bellatrix", x: 0.77, y: 0.22, accent: "#7dd3fc", size: 24,
      image: "assets/grafana.svg",
      name: { uz: "Monitoring Stack", ru: "Monitoring Stack", en: "Monitoring Stack" },
      tagline: { uz: "Grafana · Prometheus · Zabbix", ru: "Grafana · Prometheus · Zabbix", en: "Grafana · Prometheus · Zabbix" },
      desc: { uz: "To'liq monitoring yechimi: metrikalar yig'ish (Prometheus/Zabbix), chiroyli Grafana panellari va alert qoidalari — infratuzilmangizning har bir burchagi ko'z ostingizda.",
              ru: "Полное решение мониторинга: сбор метрик (Prometheus/Zabbix), красивые панели Grafana и правила оповещений — каждый уголок инфраструктуры под контролем.",
              en: "A complete monitoring solution: metrics collection (Prometheus/Zabbix), polished Grafana panels and alert rules — every corner of your infrastructure in view." },
      tags: ["Grafana", "Prometheus", "Zabbix", "node_exporter"] },

    { id: "telegram-bots", star: "Saiph", x: 0.28, y: 0.87, accent: "#34d399", size: 22,
      image: "assets/telegram-bot.svg",
      name: { uz: "Telegram Alert Botlar", ru: "Telegram-боты оповещений", en: "Telegram Alert Bots" },
      tagline: { uz: "Avtomatik xabar va boshqaruv", ru: "Авто-оповещения и управление", en: "Auto alerts and control" },
      desc: { uz: "Kritik holatlarda guruhga avtomatik xabar yuboruvchi botlar — baza, sxema, sabab, vaqt va mas'ul bilan. Inline tugmalar orqali to'g'ridan-to'g'ri javob berish.",
              ru: "Боты, автоматически отправляющие сообщения о критических ситуациях — с базой, схемой, причиной, временем и ответственным. Реакция прямо через inline-кнопки.",
              en: "Bots that auto-post critical alerts to a group — with database, schema, cause, time and owner. Respond directly via inline buttons." },
      tags: ["Telegram Bot API", "Bash", "Node.js", "Webhooks"] },

    { id: "devops", star: "Alnitak", x: 0.13, y: 0.55, accent: "#a78bfa", size: 22, icon: "gitlab",
      image: "assets/portainer.svg",
      name: { uz: "DevOps & CI/CD", ru: "DevOps & CI/CD", en: "DevOps & CI/CD" },
      tagline: { uz: "GitLab CI/CD · Docker · dev/prod zona", ru: "GitLab CI/CD · Docker · dev/prod зоны", en: "GitLab CI/CD · Docker · dev/prod zones" },
      desc: { uz: "GitLab CI/CD quvuri bilan to'liq avtomatlashtirilgan yetkazib berish: kod commit qilinishi bilan build → test → Dev zonaga, so'ng tasdiqlash bilan Prod zonaga chiqadi. Konteynerlash (Docker), Portainer boshqaruvi, Nginx reverse proxy, replikalar va rollback.",
              ru: "Полностью автоматизированная доставка через конвейер GitLab CI/CD: при коммите кода build → test → в Dev-зону, затем с подтверждением в Prod-зону. Контейнеризация (Docker), управление Portainer, Nginx reverse proxy, реплики и откат.",
              en: "Fully automated delivery via the GitLab CI/CD pipeline: on code commit build → test → Dev zone, then with approval to the Prod zone. Containerization (Docker), Portainer management, Nginx reverse proxy, replicas and rollback." },
      tags: ["GitLab CI/CD", "Docker", "Portainer", "Nginx", "Pipeline"],
      highlights: {
        uz: [
          "1 — Build :: Har commit'da Docker image avtomatik quriladi va registry'ga saqlanadi.",
          "2 — Test :: Avtomatik testlar, lint va xavfsizlik skani — sifatsiz kod o'tmaydi.",
          "3 — Deploy → Dev zona :: Har push'da dev muhitga avtomatik chiqariladi va tekshiriladi.",
          "4 — Deploy → Prod zona :: Faqat qo'lda tasdiqlash (manual approval) bilan ishlab chiqarishga; xato bo'lsa bir bosishda rollback.",
          "5 — Monitoring :: Deploy'dan keyin holat, log va alertlar — Dev va Prod alohida kuzatiladi."
        ],
        ru: [
          "1 — Build :: На каждый коммит автоматически собирается Docker-образ и сохраняется в registry.",
          "2 — Test :: Автотесты, линт и скан безопасности — некачественный код не проходит.",
          "3 — Deploy → Dev-зона :: На каждый push автоматический деплой в dev-среду и проверка.",
          "4 — Deploy → Prod-зона :: Только с ручным подтверждением (manual approval); при ошибке откат в один клик.",
          "5 — Мониторинг :: После деплоя — состояние, логи и оповещения; Dev и Prod отслеживаются отдельно."
        ],
        en: [
          "1 — Build :: Every commit auto-builds a Docker image and stores it in the registry.",
          "2 — Test :: Automated tests, lint and security scan — low-quality code is blocked.",
          "3 — Deploy → Dev zone :: Every push auto-deploys to the dev environment and is verified.",
          "4 — Deploy → Prod zone :: Production only via manual approval; one-click rollback on failure.",
          "5 — Monitoring :: Post-deploy status, logs and alerts — Dev and Prod tracked separately."
        ]
      } },

    { id: "oracle-linux", star: "Alnilam", x: 0.87, y: 0.52, accent: "#f87171", size: 22,
      image: "assets/oracle-linux.svg",
      name: { uz: "Oracle & Linux", ru: "Oracle & Linux", en: "Oracle & Linux" },
      tagline: { uz: "Baza va server infratuzilmasi", ru: "Инфраструктура баз и серверов", en: "Database & server infrastructure" },
      desc: { uz: "Oracle 19c o'rnatish, SQL tuning, tablespace/instance kuzatuvi va Linux serverlarda bash bilan avtomatlashtirish (cron). Ishonchli, kuzatib boriladigan asos.",
              ru: "Установка Oracle 19c, тюнинг SQL, мониторинг tablespace/instance и автоматизация на Linux через bash (cron). Надёжная, наблюдаемая основа.",
              en: "Oracle 19c installation, SQL tuning, tablespace/instance monitoring and bash automation on Linux (cron). A reliable, observable foundation." },
      tags: ["Oracle 19c", "SQL", "Linux", "Bash", "cron"] },

    { id: "network", star: "Mintaka", x: 0.62, y: 0.75, accent: "#22d3ee", size: 22,
      image: "assets/network-monitoring.svg",
      name: { uz: "Tarmoq Nazorati", ru: "Контроль сети", en: "Network Control" },
      tagline: { uz: "Topologiya va bandlik", ru: "Топология и нагрузка", en: "Topology and load" },
      desc: { uz: "Tarmoq topologiyasini vizualizatsiya qilish, kommutator/router/firewall holati, bandlik va latency monitoringi — uzilishlarni darhol aniqlash.",
              ru: "Визуализация топологии сети, состояние коммутаторов/роутеров/firewall, мониторинг нагрузки и задержек — мгновенное обнаружение сбоев.",
              en: "Network topology visualization, switch/router/firewall health, bandwidth and latency monitoring — instant fault detection." },
      tags: ["SNMP", "Zabbix", "Grafana", "ICMP"] },

    { id: "search-queue", star: "Meissa", x: 0.50, y: 0.10, accent: "#fbbf24", size: 20,
      image: "assets/grafana.svg",
      name: { uz: "Search & Queue", ru: "Search & Queue", en: "Search & Queue" },
      tagline: { uz: "Elasticsearch · RabbitMQ", ru: "Elasticsearch · RabbitMQ", en: "Elasticsearch · RabbitMQ" },
      desc: { uz: "Loglarni yig'ish va qidirish uchun Elasticsearch, hamda ishonchli xabar almashinuvi uchun RabbitMQ — monitoring va dashboardlar bilan birga.",
              ru: "Elasticsearch для сбора и поиска логов и RabbitMQ для надёжного обмена сообщениями — вместе с мониторингом и дашбордами.",
              en: "Elasticsearch for log collection and search, and RabbitMQ for reliable messaging — together with monitoring and dashboards." },
      tags: ["Elasticsearch", "RabbitMQ", "Kibana", "Logstash"] },
  ],

  /* -------- Constellation edges (which nodes connect, spider-web) -------- */
  constellationEdges: [
    // perimeter ring (clockwise, keeps the centre clear for the logo)
    ["search-queue", "monitoring-stack"], ["monitoring-stack", "oracle-linux"],
    ["oracle-linux", "orion-chat"], ["orion-chat", "network"],
    ["network", "telegram-bots"], ["telegram-bots", "devops"],
    ["devops", "oriondb"], ["oriondb", "search-queue"],
    // gentle arcs for a web feel
    ["oriondb", "monitoring-stack"], ["telegram-bots", "orion-chat"],
  ],

  /* -------- ORIONDB deep-dive (project.html?id=oriondb) -------- */
  oriondb: {
    features: [
      { icon: "_monitor", title: { uz: "Real vaqtli monitoring", ru: "Мониторинг в реальном времени", en: "Real-time monitoring" },
        desc: { uz: "Jonli dashboard (WebSocket), 50+ baza, svetafor plitka + ovozli signal. Leader election — bazaga 3× yuk tushmaydi.",
                ru: "Живой дашборд (WebSocket), 50+ баз, светофор-плитки + звуковой сигнал. Leader election — нет тройной нагрузки на базу.",
                en: "Live dashboard (WebSocket), 50+ databases, traffic-light tiles + audible signal. Leader election — no triple load on the database." } },
      { icon: "_db", title: { uz: "Ko'p platformali bazalar", ru: "Мультиплатформенные БД", en: "Multi-platform databases" },
        desc: { uz: "Oracle (chuqur), PostgreSQL (to'liq tahlil), ClickHouse, MongoDB, Cassandra, Kafka.",
                ru: "Oracle (глубоко), PostgreSQL (полный анализ), ClickHouse, MongoDB, Cassandra, Kafka.",
                en: "Oracle (deep), PostgreSQL (full analysis), ClickHouse, MongoDB, Cassandra, Kafka." } },
      { icon: "_chart", title: { uz: "Performance tahlili", ru: "Анализ производительности", en: "Performance analysis" },
        desc: { uz: "ASH / Wait Class drill-down, Top SQL (→ dasturchiga yuborish), locklar, sessiyalar, joblar, tablespace.",
                ru: "ASH / Wait Class drill-down, Top SQL (→ отправка разработчику), локи, сессии, джобы, tablespace.",
                en: "ASH / Wait Class drill-down, Top SQL (→ send to a developer), locks, sessions, jobs, tablespace." } },
      { icon: "_alert", title: { uz: "Aqlli alert tizimi", ru: "Умные оповещения", en: "Smart alerting" },
        desc: { uz: "Telegram bot (chart PNG + inline Ack/Snooze/Resolve), daily digest, recovery xabari, sozlanadigan chegaralar.",
                ru: "Telegram-бот (chart PNG + inline Ack/Snooze/Resolve), дайджест, уведомление о восстановлении, настраиваемые пороги.",
                en: "Telegram bot (chart PNG + inline Ack/Snooze/Resolve), daily digest, recovery notice, configurable thresholds." } },
      { icon: "_server", title: { uz: "Infratuzilma / OS", ru: "Инфраструктура / ОС", en: "Infrastructure / OS" },
        desc: { uz: "DataCenter → Rack → Server, HyperFlex/VM topologiya, fayl tizimlari, CPU/RAM/Disk (SSH yoki Prometheus/Grafana, Hybrid).",
                ru: "DataCenter → Rack → Server, топология HyperFlex/VM, файловые системы, CPU/RAM/Disk (SSH или Prometheus/Grafana, Hybrid).",
                en: "DataCenter → Rack → Server, HyperFlex/VM topology, file systems, CPU/RAM/Disk (SSH or Prometheus/Grafana, Hybrid)." } },
      { icon: "_shield", title: { uz: "Xavfsizlik / RBAC", ru: "Безопасность / RBAC", en: "Security / RBAC" },
        desc: { uz: "5 rol + superadmin, granular override (live), audit + DDL audit, AES-256, JWT, brute-force himoya.",
                ru: "5 ролей + superadmin, granular override (live), аудит + DDL-аудит, AES-256, JWT, защита от brute-force.",
                en: "5 roles + superadmin, granular live override, audit + DDL audit, AES-256, JWT, brute-force protection." } },
      { icon: "_stack", title: { uz: "Enterprise & HA", ru: "Enterprise и HA", en: "Enterprise & HA" },
        desc: { uz: "HA (pgpool + repmgr, 3 replika), 50+ baza masshtab, doimiy backup, vCenter import, Saldo moduli, Tizim konsoli.",
                ru: "HA (pgpool + repmgr, 3 реплики), масштаб 50+ баз, постоянный backup, импорт vCenter, модуль «Сальдо», системная консоль.",
                en: "HA (pgpool + repmgr, 3 replicas), 50+ database scale, continuous backup, vCenter import, Balance module, system console." } },
      { icon: "_globe", title: { uz: "Platforma", ru: "Платформа", en: "Platform" },
        desc: { uz: "UZ/RU/EN interfeys, real-time WebSocket, responsive / dark mavzu, Docker bilan tez joriy etish.",
                ru: "Интерфейс UZ/RU/EN, real-time WebSocket, responsive / тёмная тема, быстрое внедрение через Docker.",
                en: "UZ/RU/EN UI, real-time WebSocket, responsive / dark theme, fast Docker deployment." } },
      { icon: "_lock", title: { uz: "Litsenziya & White-label", ru: "Лицензия и White-label", en: "License & white-label" },
        desc: { uz: "Basic/Pro/Max tariflar, Ed25519 litsenziya, per-mijoz brend (rebuild'siz), ma'lumot yo'qotmasdan upgrade.",
                ru: "Тарифы Basic/Pro/Max, лицензия Ed25519, бренд под каждого клиента (без rebuild), апгрейд без потери данных.",
                en: "Basic/Pro/Max tiers, Ed25519 license, per-client branding (no rebuild), upgrade without data loss." } },
    ],

    /* integrations shown with brand logos (simpleicons slug, or _key for inline) */
    integrations: [
      { name: "Oracle", slug: "oracle", logo: "assets/oracle-logo.png" },
      { name: "PostgreSQL", slug: "postgresql" },
      { name: "ClickHouse", slug: "clickhouse" },
      { name: "MongoDB", slug: "mongodb" },
      { name: "Cassandra", slug: "apachecassandra" },
      { name: "Kafka", slug: "apachekafka" },
      { name: "Telegram", slug: "telegram" },
      { name: "Grafana", slug: "grafana" },
      { name: "Prometheus", slug: "prometheus" },
      { name: "Portainer", slug: "portainer" },
      { name: "GitLab", slug: "gitlab" },
      { name: "Nginx", slug: "nginx" },
      { name: "Docker", slug: "docker" },
      { name: "VMware vCenter", slug: "vmware" },
      { name: "Cisco HyperFlex", slug: "cisco" },
    ],

    /* difference vs Oracle EM / ASHviewer */
    comparison: [
      { feature: { uz: "Bir nechta baza bitta oynada", ru: "Несколько баз в одном окне", en: "Many databases in one screen" }, em: "part", ash: "no", orion: "yes" },
      { feature: { uz: "Real-time WebSocket push", ru: "Real-time WebSocket push", en: "Real-time WebSocket push" }, em: "no", ash: "no", orion: "yes" },
      { feature: { uz: "Telegram alert + inline tugma", ru: "Telegram-оповещения + inline", en: "Telegram alerts + inline buttons" }, em: "no", ash: "no", orion: "yes" },
      { feature: { uz: "ASH wait class drill-down", ru: "ASH wait class drill-down", en: "ASH wait class drill-down" }, em: "yes", ash: "yes", orion: "yes" },
      { feature: { uz: "Svetafor + ovozli signal", ru: "Светофор + звук", en: "Traffic-light + audio" }, em: "no", ash: "no", orion: "yes" },
      { feature: { uz: "Lokal, internetsiz ishlaydi", ru: "Локально, без интернета", en: "Runs locally, no internet" }, em: "part", ash: "yes", orion: "yes" },
      { feature: { uz: "Multi-platform (PG/Mongo/Kafka)", ru: "Мульти-платформа (PG/Mongo/Kafka)", en: "Multi-platform (PG/Mongo/Kafka)" }, em: "no", ash: "no", orion: "yes" },
      { feature: { uz: "Narx (litsenziya)", ru: "Стоимость (лицензия)", en: "Cost (license)" }, em: "high", ash: "mid", orion: "low" },
      { feature: { uz: "3 tilli interfeys (UZ/RU/EN)", ru: "Интерфейс на 3 языках", en: "Trilingual UI (UZ/RU/EN)" }, em: "no", ash: "no", orion: "yes" },
      { feature: { uz: "Per-user ruxsat + audit", ru: "Права на пользователя + аудит", en: "Per-user permissions + audit" }, em: "yes", ash: "no", orion: "yes" },
    ],

    /* release history (newest first) */
    releases: [
      { version: "v2.11", date: "2026", items: {
        uz: ["Faqat ichki tarmoq rejimi (ACCESS_RESTRICT)", "Dasturchiga Portainer service biriktirish", "HA stack frontend real mijoz IP (mode: host)"],
        ru: ["Режим только внутренней сети (ACCESS_RESTRICT)", "Привязка Portainer-сервиса к разработчику", "Реальный IP клиента во frontend HA (mode: host)"],
        en: ["Internal-network-only mode (ACCESS_RESTRICT)", "Attach Portainer service to a developer", "Real client IP in HA frontend (mode: host)"] } },
      { version: "v2.10", date: "2026", items: {
        uz: ["Superadmin + per-user ruxsat matritsasi", "Tizim konsoli (integratsiya holati + xatolar)", "HyperFlex/VM topologiyasi", "Multi-DB asos: PostgreSQL/ClickHouse/Mongo/Kafka", "Export/Import, to'liq 3 tilli admin"],
        ru: ["Superadmin + матрица прав на пользователя", "Системная консоль (статус интеграций + ошибки)", "Топология HyperFlex/VM", "Основа Multi-DB: PostgreSQL/ClickHouse/Mongo/Kafka", "Export/Import, полностью 3-язычная админка"],
        en: ["Superadmin + per-user permission matrix", "System console (integration status + errors)", "HyperFlex/VM topology", "Multi-DB foundation: PostgreSQL/ClickHouse/Mongo/Kafka", "Export/Import, fully trilingual admin"] } },
      { version: "v2.9", date: "2025", items: {
        uz: ["Prometheus/Grafana datasource proxy", "Nginx reverse proxy qo'llanmasi (4 variant)", "Ketma-ket docker compose startup", "Oracle pool lock refinement"],
        ru: ["Прокси datasource Prometheus/Grafana", "Руководство Nginx reverse proxy (4 варианта)", "Последовательный старт docker compose", "Доработка Oracle pool lock"],
        en: ["Prometheus/Grafana datasource proxy", "Nginx reverse proxy guide (4 variants)", "Sequential docker compose startup", "Oracle pool lock refinement"] } },
    ],
  },

  /* -------- PRICING: ORIONDB packages (basic / pro / max) -------- */
  pricing: {
    note: { uz: "Narxlar taxminiy ko'rsatilgan, aniq narx loyiha hajmiga qarab kelishiladi.",
            ru: "Цены указаны ориентировочно, точная стоимость согласуется по объёму проекта.",
            en: "Prices are indicative; the exact cost is agreed based on project scope." },
    trial: {
      badge: { uz: "BEPUL", ru: "БЕСПЛАТНО", en: "FREE" },
      title: { uz: "1 ta baza uchun bepul sinov", ru: "Бесплатный пробный период — 1 база", en: "Free trial — 1 database" },
      desc: { uz: "ORIONDB'ni 1 ta bazada to'liq imkoniyatlar bilan bepul sinab ko'ring — karta talab qilinmaydi.",
              ru: "Попробуйте ORIONDB бесплатно на 1 базе со всеми возможностями — карта не нужна.",
              en: "Try ORIONDB free on 1 database with full features — no card required." },
      cta: { uz: "Bepul boshlash", ru: "Начать бесплатно", en: "Start free" } },
    packages: [
      { key: "basic", annual: "free", perpetual: "free", highlight: false,
        tagline: { uz: "Bepul boshlash uchun", ru: "Чтобы начать бесплатно", en: "To get started free" },
        features: {
          uz: ["1 ta baza — bepul", "Real-time dashboard", "Svetafor indikatorlar", "Telegram alert (asosiy)", "Audit log"],
          ru: ["1 база — бесплатно", "Real-time дашборд", "Светофоры", "Telegram-оповещения (базовые)", "Аудит-лог"],
          en: ["1 database — free", "Real-time dashboard", "Traffic-light tiles", "Telegram alerts (basic)", "Audit log"] },
        integrations: ["Oracle", "PostgreSQL", "Telegram"] },

      { key: "pro", annual: "$500", perpetual: "$2 500", highlight: true,
        tagline: { uz: "O'rta korxonalar uchun", ru: "Для средних компаний", en: "For mid-size companies" },
        features: {
          uz: ["25 tagacha baza", "Basic'dagi hammasi", "ASH wait class drill-down", "SSH / Prometheus server monitoring", "Inline Telegram tugmalar + digest", "RBAC + per-user ruxsat", "3 tilli interfeys", "Ustuvor qo'llab-quvvatlash"],
          ru: ["До 25 баз", "Всё из Basic", "ASH wait class drill-down", "SSH / Prometheus мониторинг серверов", "Inline Telegram-кнопки + дайджест", "RBAC + права на пользователя", "Интерфейс на 3 языках", "Приоритетная поддержка"],
          en: ["Up to 25 databases", "Everything in Basic", "ASH wait class drill-down", "SSH / Prometheus server monitoring", "Inline Telegram buttons + digest", "RBAC + per-user permissions", "Trilingual UI", "Priority support"] },
        integrations: ["Oracle", "PostgreSQL", "Telegram", "Grafana", "Prometheus", "Portainer"] },

      { key: "max", annual: "$1 500", perpetual: "negotiate", highlight: false,
        tagline: { uz: "Enterprise / banklar uchun", ru: "Для enterprise / банков", en: "For enterprise / banks" },
        features: {
          uz: ["Cheksiz baza", "Pro'dagi hammasi", "HA (PostgreSQL replikatsiya + pgpool)", "Multi-platform (ClickHouse/Mongo/Cassandra/Kafka)", "HyperFlex/VM topologiyasi", "Data Center / Rack vizualizatsiyasi", "Faqat ichki tarmoq rejimi", "Custom SQL monitoring", "24/7 + on-site qo'llab-quvvatlash"],
          ru: ["Неограниченно баз", "Всё из Pro", "HA (репликация PostgreSQL + pgpool)", "Мульти-платформа (ClickHouse/Mongo/Cassandra/Kafka)", "Топология HyperFlex/VM", "Визуализация ЦОД / стоек", "Режим только внутренней сети", "Кастомный SQL-мониторинг", "Поддержка 24/7 + on-site"],
          en: ["Unlimited databases", "Everything in Pro", "HA (PostgreSQL replication + pgpool)", "Multi-platform (ClickHouse/Mongo/Cassandra/Kafka)", "HyperFlex/VM topology", "Data Center / Rack visualization", "Internal-network-only mode", "Custom SQL monitoring", "24/7 + on-site support"] },
        integrations: ["Oracle", "PostgreSQL", "Telegram", "Grafana", "Prometheus", "Portainer", "Nginx", "LDAP/AD", "vCenter/HyperFlex", "ClickHouse/Mongo/Kafka"] },
    ],
    /* package-difference matrix: value = "yes"/"no" or a text string */
    matrix: [
      { f: { uz: "Bazalar soni", ru: "Кол-во баз", en: "Databases" }, basic: "1", pro: "25", max: "∞" },
      { f: { uz: "Real-time dashboard", ru: "Real-time дашборд", en: "Real-time dashboard" }, basic: "yes", pro: "yes", max: "yes" },
      { f: { uz: "Telegram alert", ru: "Telegram-оповещения", en: "Telegram alerts" }, basic: "yes", pro: "yes", max: "yes" },
      { f: { uz: "ASH wait class drill-down", ru: "ASH wait class drill-down", en: "ASH wait class drill-down" }, basic: "no", pro: "yes", max: "yes" },
      { f: { uz: "SSH / Prometheus monitoring", ru: "SSH / Prometheus мониторинг", en: "SSH / Prometheus monitoring" }, basic: "no", pro: "yes", max: "yes" },
      { f: { uz: "Portainer integratsiyasi", ru: "Интеграция Portainer", en: "Portainer integration" }, basic: "no", pro: "yes", max: "yes" },
      { f: { uz: "RBAC + per-user ruxsat", ru: "RBAC + права на пользователя", en: "RBAC + per-user permissions" }, basic: "no", pro: "yes", max: "yes" },
      { f: { uz: "3 tilli interfeys", ru: "Интерфейс на 3 языках", en: "Trilingual UI" }, basic: "no", pro: "yes", max: "yes" },
      { f: { uz: "HA (replikatsiya + pgpool)", ru: "HA (репликация + pgpool)", en: "HA (replication + pgpool)" }, basic: "no", pro: "no", max: "yes" },
      { f: { uz: "Multi-platform (Mongo/Kafka…)", ru: "Мульти-платформа (Mongo/Kafka…)", en: "Multi-platform (Mongo/Kafka…)" }, basic: "no", pro: "no", max: "yes" },
      { f: { uz: "HyperFlex/VM topologiyasi", ru: "Топология HyperFlex/VM", en: "HyperFlex/VM topology" }, basic: "no", pro: "no", max: "yes" },
      { f: { uz: "Faqat ichki tarmoq rejimi", ru: "Режим только внутренней сети", en: "Internal-network-only mode" }, basic: "no", pro: "no", max: "yes" },
      { f: { uz: "Qo'llab-quvvatlash", ru: "Поддержка", en: "Support" }, basic: { uz: "Email", ru: "Email", en: "Email" }, pro: { uz: "Ustuvor", ru: "Приоритет", en: "Priority" }, max: { uz: "24/7 + on-site", ru: "24/7 + on-site", en: "24/7 + on-site" } },
    ],
  },

  /* -------- CLIENTS (logos) -------- */
  clients: [
    { name: "NexaBank", logo: "assets/client-1.svg" },
    { name: "DataSoft", logo: "assets/client-2.svg" },
    { name: "TezkorIT", logo: "assets/client-3.svg" },
    { name: "CloudMesh", logo: "assets/client-4.svg" },
  ],

  /* -------- TESTIMONIALS -------- */
  testimonials: [
    { name: "Akmal Karimov", company: "NexaBank", avatar: "A",
      role: { uz: "IT direktor", ru: "IT-директор", en: "IT Director" },
      quote: { uz: "ORIONDB bizning Oracle bazalarni kuzatishni butunlay o'zgartirdi. Endi muammoni mijoz sezishidan oldin bilamiz.",
               ru: "ORIONDB полностью изменил наш мониторинг баз Oracle. Теперь мы узнаём о проблеме раньше клиента.",
               en: "ORIONDB completely changed how we monitor our Oracle databases. Now we know about issues before the client does." } },
    { name: "Дмитрий Соколов", company: "DataSoft", avatar: "Д",
      role: { uz: "DevOps lead", ru: "DevOps-лид", en: "DevOps Lead" },
      quote: { uz: "Lokal chat va monitoring stack'ni bir hafta ichida o'rnatib berishdi. Professional va tez jamoa.",
               ru: "Локальный чат и стек мониторинга развернули за неделю. Профессиональная и быстрая команда.",
               en: "They deployed our local chat and monitoring stack within a week. A professional and fast team." } },
    { name: "Bobur Aliyev", company: "TezkorIT", avatar: "B",
      role: { uz: "Bosh muhandis", ru: "Главный инженер", en: "Chief Engineer" },
      quote: { uz: "Telegram alert botlari tunda ham bizni xabardor qiladi. Reaksiya vaqtimiz bir necha barobar tezlashdi.",
               ru: "Telegram-боты оповещают нас даже ночью. Время реакции ускорилось в разы.",
               en: "The Telegram alert bots notify us even at night. Our response time improved several-fold." } },
  ],

  /* -------- CONTACT -------- */
  contact: {
    phone: "+998 95 662 82 26",
    phoneRaw: "+998956628226",
    telegram: "Shuxratov_Behruz",
    email: "behruzshuxratov58@gmail.com",
    linkedin: "https://www.linkedin.com/in/shuxratov-behruz-2323233a6/",
    resume: "https://behruzops.github.io/portfolio/resume.html",
  },
};
